language: python
python:
  - 3.6
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n py21-dev python=$TRAVIS_PYTHON_VERSION;
  - source activate py21-dev
  - conda env update -f environment.yml
  - pip install coverage
  - pip install codecov
  - python setup.py install
script: pytest
after_success:
  - codecov